version: '3.8'

services:
  # Backend API
  api:
    build:
      context: ../
      dockerfile: deployment/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql://smarthistory:password@db:5432/smarthistory
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:5174
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - smarthistory-network

  # Frontend (for production deployment)
  frontend:
    build:
      context: ../
      dockerfile: deployment/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - smarthistory-network

  # Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: smarthistory
      POSTGRES_USER: smarthistory
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - smarthistory-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - smarthistory-network

volumes:
  postgres_data:
  redis_data:

networks:
  smarthistory-network:
    driver: bridge